const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const elements=new Map(),storage=new Map();
function element(id){if(!elements.has(id))elements.set(id,{value:id==='captainFilter'?'all':'',innerHTML:'',textContent:'',validity:{valid:true},listeners:{},addEventListener(type,fn){this.listeners[type]=fn},setAttribute(){},closest(){return {hidden:false}}});return elements.get(id)}
const context=vm.createContext({console,Intl,Date,Map,document:{addEventListener(){},getElementById:element,querySelectorAll:()=>[]},window:{addEventListener(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},AbortController,setTimeout,clearTimeout});
const html=fs.readFileSync('traghettamenti.html','utf8');
vm.runInContext(html.match(/<script>\s*(const TURNI[\s\S]*?)<\/script>/)[1],context);
vm.runInContext(fs.readFileSync('assets/operations.js','utf8'),context);
const run=code=>vm.runInContext(code,context);
run("captainDate='2026-10-01';captainShift='mattina';loadCaptain();renderCaptainTrains()");
assert.equal(run('captainState.names.length'),6);
assert.equal(run('captainState.assignments[534]'),'TI');assert.equal(run('captainState.assignments[1956]'),'303');
run("captainState.names[5]='Sesto';captainState.assignments[727]=5;renderCaptainTrains()");
assert.equal(run('captainSuggestions(captainServices().find(t=>t.id===723))[0].slot'),5);
assert.equal(run('captainSuggestions(captainServices().find(t=>t.id===703)).length'),0);
assert.equal(run('captainSuggestions(captainServices().find(t=>t.id===1956)).length'),0);
assert.match(element('captainTrains').innerHTML,/data-suggest="723"/);
element('captainTrains').listeners.click({target:{closest:()=>({dataset:{suggest:'723',slot:'5'}})}});
assert.equal(run('captainState.assignments[723]'),5);
run('captainState.completed[534]=true;saveCaptain();loadCaptain()');
assert.equal(run('captainState.names[5]'),'Sesto');assert.equal(run('captainState.assignments[723]'),5);assert.equal(run('captainState.completed[534]'),true);
run("captainDate='2026-10-04';loadCaptain();captainState.names[0]='Tizio';captainState.assignments[727]=0");
assert.equal(run('captainState.assignments[1956]'),undefined);assert.equal(run('captainSuggestions(captainServices().find(t=>t.id===1956))[0].slot'),0);
run("captainState.names[1]='Caio';captainState.assignments[723]=1");
assert.equal(run('captainSuggestions(captainServices().find(t=>t.id===723)).length'),0);assert.equal(run('captainSuggestions(captainServices().find(t=>t.id===1956)).length'),2);
run("captainState.names[0]='';delete captainState.assignments[727]");
assert.equal(run('captainSuggestions(captainServices().find(t=>t.id===1956)).length'),1);
storage.set('traghettamenti.capoturno.v1.2026-10-02.mattina',JSON.stringify({names:['Legacy','','','',''],assignments:{727:0,534:0,1956:0},completed:{727:true}}));
run("captainDate='2026-10-02';loadCaptain()");assert.equal(run('captainState.names.length'),6);assert.equal(run('captainState.assignments[727]'),0);assert.equal(run('captainState.completed[727]'),true);assert.equal(run('captainState.assignments[534]'),'TI');assert.equal(run('captainState.assignments[1956]'),'303');
run("captainShift='pomeriggio';loadCaptain()");
assert.equal(run('captainState.assignments[591]'),'TI');assert.equal(run('captainState.assignments[774]'),'TI');assert.equal(run('captainState.assignments[707]'),undefined);
run("captainDate='2026-10-03';captainState.names[0]='Test';captainState.assignments[540]=0");
assert.equal(run('captainSuggestions(captainServices().find(t=>t.id===728))[0].slot'),0);assert.equal(run('captainServices().some(t=>t.id===598)'),false);
run("captainShift='notte';loadCaptain();captainState.names[0]='Notte';captainState.assignments[774]=0");assert.equal(run('captainSuggestions(captainServices().find(t=>t.id===704))[0].slot'),0);
console.log('PASS: six slots, TI/303 automatic responsibility, weekday exceptions, roster suggestions, confirmation, no overwrites, persistence, legacy migration, excluded trains and shift isolation.');
